import { C, FONT } from '../lib/tokens'
import { usePortfolio, type Language } from '../lib/portfolio-context'

interface NavProps { scrolled: boolean; mobileOpen: boolean; setMobileOpen: (v: boolean) => void; scrollTo: (id: string) => void }
export default function Nav({ scrolled, mobileOpen, setMobileOpen, scrollTo }: NavProps) {
  const { language, setLanguage, toggleTheme, theme, t } = usePortfolio()
  const links = [{ label: t.nav.work, id: 'work' }, { label: t.nav.about, id: 'about' }, { label: t.nav.skills, id: 'skills' }, { label: t.nav.contact, id: 'contact' }]
  return <header className={scrolled ? 'nav-scrolled' : undefined} style={{ position: 'fixed', inset: '0 0 auto', zIndex: 200, backgroundColor: scrolled ? 'color-mix(in srgb, var(--bg) 88%, transparent)' : 'transparent', backdropFilter: scrolled ? 'blur(20px)' : 'none', borderBottom: `1px solid ${scrolled ? C.border : 'transparent'}`, transition: 'all .3s ease' }}><div style={{ maxWidth: 1440, margin: '0 auto', padding: '0 clamp(20px,4vw,72px)', height: 62, display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}><button onClick={() => window.scrollTo({ top: 0, behavior: 'smooth' })} style={{ fontFamily: FONT.sans, fontWeight: 700, fontSize: 17, color: C.fg, background: 'none', border: 'none', cursor: 'pointer', padding: 0 }}>HB<span style={{ color: C.accent }}>.</span></button><nav className="hide-mobile" style={{ display: 'flex', alignItems: 'center', gap: 28 }}>{links.map((link) => <button key={link.id} onClick={() => scrollTo(link.id)} style={{ fontFamily: FONT.sans, fontSize: 13, color: C.fg2, background: 'none', border: 'none', cursor: 'pointer', padding: '4px 0' }}>{link.label}</button>)}<div className="nav-controls"><select aria-label={t.nav.language} value={language} onChange={(e) => setLanguage(e.target.value as Language)}><option value="en">EN</option><option value="fr">FR</option><option value="ar">AR</option></select><button aria-label={t.nav.theme} onClick={toggleTheme} className="theme-button">{theme === 'dark' ? '☼' : '◐'}</button></div><span className="available-pill"><span className="pulse-dot" />{t.nav.available}</span></nav><button className="hide-desktop menu-button" onClick={() => setMobileOpen(!mobileOpen)} aria-label={t.nav.menu} aria-expanded={mobileOpen}><span /><span /><span /></button></div>{mobileOpen && <div className="mobile-menu-enter mobile-menu"><div className="mobile-controls"><select aria-label={t.nav.language} value={language} onChange={(e) => setLanguage(e.target.value as Language)}><option value="en">EN</option><option value="fr">FR</option><option value="ar">AR</option></select><button aria-label={t.nav.theme} onClick={toggleTheme} className="theme-button">{theme === 'dark' ? '☼' : '◐'}</button></div>{links.map((link) => <button key={link.id} onClick={() => scrollTo(link.id)}>{link.label}</button>)}<span className="mobile-available"><span className="pulse-dot" />{t.nav.available}</span></div>}</header>
}
